# -*- coding: utf-8 -*-
"""Bubblesort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15n0qa9EYu0fNt_86L2JJJdGtOKPbfpNV
"""

def bubblesort(arr):
  n = len(arr)
  for i in range(n-1):
    for j in range(n-1):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]

array = []
size = int(input("Enter the size of the Array: "))
for i in range(size):
  val = input(f"Enter {i+1} value: ")
  array.append(val)
print("Sorted Array\n")
bubblesort(array)
for i in range(size):
  print(array[i])

def asscending(arr):
  n = len(arr)
  for i in range(n-1):
    for j in range(n-1):
      if arr[j]<arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]

array = []
size = int(input("Enter the size of the Array: "))
for i in range(size):
  val = input(f"Enter {i+1} value: ")
  array.append(val)
print("Sorted Array\n")
asscending(array)
for i in range(size):
  print(array[i])

def alphabetorder(arr):
  n = len(arr)
  for i in range(n-1):
    for j in range(n-1):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1] = arr[j+1],arr[j]

array = []
size = int(input("Enter the size of the Array: "))
for i in range(size):
  val = input(f"Enter {i+1} value: ")
  array.append(val)
print("Sorted Array\n")
alphabetorder(array)
for i in range(size):
  print(array[i])