# -*- coding: utf-8 -*-
"""labselectionsort.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G1Zj2NXGX0HAlIj8BVYvF52gp5-gNXdP
"""

def selectionsort(array):
  n = len (array)
  for i in range(n):
    min_index = i 
    for j in range(i + 1 ,n):
      if array[min_index]>array[j]:
        min_index = j 
    array[i],array[min_index] = array[min_index],array[i]

numbers = input("Enter any Numbers (Seperated by Commas): ").split(",")
arraytosort = []
for i in numbers:
   arraytosort.append(int(i))
selectionsort(arraytosort)
for i in range(len(arraytosort)):
  print(arraytosort[i],end= "\n")

def selectionsort(array):
  n = len (array)
  for i in range(n):
    min_index = i 
    for j in range(i + 1 ,n):
      if array[min_index]<array[j]:
        min_index = j 
    array[i],array[min_index] = array[min_index],array[i]
  
numbers = input("Enter any Numbers (Seperated by Commas): ").split(",")
arraytosort = []
for i in numbers:
   arraytosort.append(int(i))
selectionsort(arraytosort)
for i in range(len(arraytosort)):
  print(arraytosort[i],end= "\n")

def selectionsort(array):
  n = len (array)
  for i in range(n):
    min_index = i 
    for j in range(i + 1 ,n):
      if array[min_index]<array[j]:
        min_index = j 
    array[i],array[min_index] = array[min_index],array[i]
  
arraytosort  = input("Enter Your Name (Seperated by Spaces): ").split(" ")
selectionsort(arraytosort)
for i in range(len(arraytosort)):
  print(arraytosort[i],end= "\n")

def selectionsort(array):
  n = len (array)
  for i in range(n):
    min_index = i 
    for j in range(i + 1 ,n):
      if array[min_index]>array[j]:
        min_index = j 
    array[i],array[min_index] = array[min_index],array[i]
  
arraytosort  = input("Enter Your Name (Seperated by Spaces): ").split(" ")
selectionsort(arraytosort)
for i in range(len(arraytosort)):
  print(arraytosort[i],end= "\n")